name: ecode_fess
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  sizer: ^2.0.15
  cached_network_image: ^3.3.1
  another_flushbar: ^1.12.30
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sliding_up_panel: ^2.0.0+1
  equatable: ^2.0.5
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.5
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/